title: "My Physics Blog"
description: "LaTeX 수식이 깔끔하게 표시되는 블로그"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

just_the_docs:
  mathjax: true # LaTeX 수식 지원
  search_enabled: true
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
baseurl: "" # 로컬에서는 빈 값
url: "https://piw1995.github.io" # GitHub Pages URL

defaults:
  - scope:
      path: ""
    values:
      favicon: /favicon.ico
